version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/start_app.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/stop_app.sh
      timeout: 60
      runas: root